### PR TITLE
030360

### PR DESCRIPTION
**Pull request by awilson61363**
modified "Line" statement under 030360:
line: "-a always,exit -F path={{ item }} -F auid>=1000 -F auid!=4294967295 -k setuid/setgid\r\n -a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid\r\n -a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid\r\n -a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid\r\n -a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid"

### CODE REVIEW

**Review by robinje — CHANGES_REQUESTED** [review]
Please remove the commented out line.

Please please specify the change that you are making.

**Comment by awilson61363** [comment]
"-a always,exit -F path={{ item }} -F auid>=1000 -F auid!=4294967295 -k setuid/setgid\r\n

Added following line per Nessus Scan to the original "line" statement above :

-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid\r\n
 -a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid\r\n 
-a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid\r\n 
-a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid" 

Ansible needed to see a carriage return and new line after each line entry . (\r\n) was added to the end of each line entry.

**Review by PaulWaldo — CHANGES_REQUESTED** [review]
This change adds the 4 lines after every instance of lines that have "-F auid!=4294967295".  If you look at the output of the successful scan, you cans where the required line matched numerous times (it is duplicated).  My reading of the STIG indicates it should appear only once for 32-bit architecture.  I might suggest the following change instead:
```
regexp: "^[\\s]*-a[\\s]+always,exit[\\s]+-F[\\s]+arch=b32[\\s]+-S[\\s]+execve[\\s]+-C[\\s]+gid!=egid[\\s]+-F[\\s]+egid=0[\\s]+-k[\\s]+setgid[\\s]*$"
line: "-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid"
```

**Review by awilson61363 — COMMENTED** [review]
Changed Fix-cat2.yml . 
Configure the operating system to audit the execution of privileged functions.
Added the following lines to "/etc/audit/rules.d/audit.rules"

-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid
-a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid
-a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid
-a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid

**Review by PaulWaldo — APPROVED** [review]
👍

**Comment by PaulWaldo** [comment]
@awilson61363 Changes approved, but you have conflicts.  Please resolve and we can merge.

**Comment by PaulWaldo** [comment]
Resolved by PR https://github.com/ampsight/RHEL7-STIG/pull/38

**Pull request closed without merging**
