### PR TITLE
RHEL-07-030330

### PR DESCRIPTION
**Pull request by jvitray**

### CODE REVIEW

**Review by PaulWaldo — COMMENTED** [review]
Please remove commented lines

**Comment by PaulWaldo** [comment]
@robinje this PR indeed resolves the STIG as implemented, but the check itself is completely broken.  What is the best course of action for this?

**Review by PaulWaldo — CHANGES_REQUESTED** [review]
Please remove commented lines

**Comment by jvitray** [comment]
Removed commented lines.

**Pull request merged**
